# Netlify deployment configuration
[build]
  publish = "dist"
  command = "npm run build:production"
  functions = "netlify/functions"

# Environment variables for build
[build.environment]
  NODE_ENV = "production"
  VITE_DEPLOY_TARGET = "netlify"

# Redirect rules for SPA
[[redirects]]
  from = \"/*\"
  to = \"/index.html\"
  status = 200

# Security headers
[[headers]]
  for = \"/*\"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://apis.google.com https://*.firebaseapp.com https://*.googleapis.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https: blob: https://res.cloudinary.com; connect-src 'self' https://*.firebaseapp.com https://*.googleapis.com https://*.firebaseio.com wss://*.firebaseio.com https://api.cloudinary.com; frame-src https://*.firebaseapp.com;"

# Cache headers for static assets
[[headers]]
  for = \"/assets/*\"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache headers for service worker
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"